const allProperties = [
  {
    id: "1",
    property_name: "dummy 1",
    property_type: "residential",
    for_sale: true,
    price: "1000$",
    bedrooms: 3,
    bathrooms: 3,
    area: "200sqft",
    type: "apartment",
    thumb_img: "./properties/images/338.jpg",
    location: "Dhanori Pune",
    images: [
      "./properties/images/338.jpg",
      "./properties/images/395.jpg",
      "./properties/images/1777.jpg",
      "./properties/images/9954.jpg",
    ],
    deposit: 5000,
    amenities: ["swimming pool", "security cabin", "cctv surveilance"],
    add_date: "11-11-2024",
    description: "Best Properties for rent this property is locaited",
  },
  {
    id: "2",
    property_name: "dummy 2",
    property_type: "commercial",
    for_sale: false,
    price: "1000$",
    bedrooms: 3,
    bathrooms: 3,
    area: "200sqft",
    type: "apartment",
    thumb_img: "./properties/images/338.jpg",
    location: "Kharadi Pune",
    images: [
      "./properties/images/338.jpg",
      "./properties/images/395.jpg",
      "./properties/images/1777.jpg",
      "./properties/images/9954.jpg",
    ],
    deposit: 5000,
    amenities: ["swimming pool", "security cabin", "cctv surveilance"],
    add_date: "11-11-2024",
    description: "Best Properties for rent this property is locaited",
  },
  {
    id: "3",
    property_name: "dummy 3",
    property_type: "residential",
    for_sale: true,
    price: "1000$",
    bedrooms: 3,
    bathrooms: 3,
    area: "200sqft",
    type: "apartment",
    thumb_img: "./properties/images/338.jpg",
    location: "Vimannagar Pune",
    images: [
      "./properties/images/338.jpg",
      "./properties/images/395.jpg",
      "./properties/images/1777.jpg",
      "./properties/images/9954.jpg",
    ],
    deposit: 5000,
    amenities: ["swimming pool", "security cabin", "cctv surveilance"],
    add_date: "11-11-2024",
    description: "Best Properties for rent this property is locaited",
  },
  {
    id: "4",
    property_name: "dummy 4",
    property_type: "residential",
    for_sale: true,
    price: "1000$",
    bedrooms: 3,
    bathrooms: 3,
    area: "200sqft",
    type: "apartment",
    thumb_img: "./properties/images/338.jpg",
    location: "Mundhwa Pune",
    images: [
      "./properties/images/338.jpg",
      "./properties/images/395.jpg",
      "./properties/images/1777.jpg",
      "./properties/images/9954.jpg",
    ],
    deposit: 5000,
    amenities: ["swimming pool", "security cabin", "cctv surveilance"],
    add_date: "11-11-2024",
    description: "Best Properties for rent this property is locaited",
  },
  {
    id: "5",
    property_name: "dummy 5",
    property_type: "residential",
    for_sale: false,
    price: "1000$",
    bedrooms: 3,
    bathrooms: 3,
    area: "200sqft",
    type: "apartment",
    thumb_img: "./properties/images/338.jpg",
    location: "Keshavnagar Pune",
    images: [
      "./properties/images/338.jpg",
      "./properties/images/395.jpg",
      "./properties/images/1777.jpg",
      "./properties/images/9954.jpg",
    ],
    deposit: 5000,
    amenities: ["swimming pool", "security cabin", "cctv surveilance"],
    add_date: "11-11-2024",
    description: "Best Properties for rent this property is locaited",
  },
];

export default allProperties;
